# Generated by Django 5.2 on 2025-04-08 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_agendamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='date_created',
            new_name='data_de_criacao',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='bolsista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_bolsista', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('Solicitado', 'Solicitado'), ('Andamento', 'Andamento'), ('Finalizado', 'Finalizado')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_cliente', to=settings.AUTH_USER_MODEL),
        ),
    ]
