# Generated by Django 5.2 on 2025-04-08 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_rename_date_created_agendamento_data_de_criacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='bolsista',
            new_name='bolsista_id',
        ),
        migrations.RenameField(
            model_name='agendamento',
            old_name='cliente',
            new_name='cliente_id',
        ),
    ]
