# Generated by Django 5.2 on 2025-04-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_rename_bolsista_agendamento_bolsista_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='motivo',
            field=models.TextField(null=True),
        ),
    ]
