# Generated by Django 5.2 on 2025-04-08 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0005_agendamento_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='data_prevista',
            field=models.DateField(default=datetime.datetime(2025, 4, 8, 20, 20, 17, 721089, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_final',
            field=models.DateField(null=True),
        ),
    ]
