# Generated by Django 5.2 on 2025-04-08 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0007_alter_agendamento_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='bolsista_id',
            new_name='bolsista',
        ),
        migrations.RenameField(
            model_name='agendamento',
            old_name='cliente_id',
            new_name='cliente',
        ),
    ]
